local policy = dofile(arg[1])
local json = require('cjson')
local count = 0
local function equal(actual, expected, label)
	assert(actual == expected, label .. ': expected ' .. tostring(expected) .. ', got ' .. tostring(actual))
	count = count + 1
end
local function tick(state, status, now, boot)
	return policy.step(state, status, now, boot or 'boot-a')
end
local s, events = tick({}, 'OL', 100)
equal(#events, 0, 'healthy startup is silent')
s, events = tick(s, 'OB DISCHRG', 120)
equal(events[1], 'on-battery', 'first outage announces immediately')
equal(s.outage_since, 120, 'outage starts at observation')
s, events = tick(s, 'OB', 419)
equal(#events, 0, 'no early five-minute warning')
s, events = tick(s, 'OB', 420)
equal(events[1], 'five-minutes', 'warning at exactly 300 seconds')
s, events = tick(s, 'OB', 421)
equal(#events, 0, 'warning is emitted once')
s = json.decode(json.encode(s))
s, events = tick(s, 'OB', 720)
equal(events[1], 'shutdown', 'restart preserves ten-minute deadline')
s, events = tick(s, 'OB', 721)
equal(#events, 0, 'no duplicate shutdown event')
s, events = tick(s, 'OL', 722)
equal(events[1], 'online', 'restoration is announced')
equal(s.outage_since, nil, 'restoration clears outage')
s, events = tick(s, 'OB', 800)
equal(s.outage_since, 800, 'new outage has a new deadline')
s, events = tick(s, nil, 850)
equal(events[1], 'communication-lost', 'USB loss is reported')
equal(s.outage_since, 800, 'USB loss does not cancel known outage')
s, events = tick(s, nil, 1400)
equal(events[#events], 'shutdown', 'USB loss cannot defer a known outage indefinitely')
s, events = tick({}, nil, 100)
equal(events[1], 'communication-lost', 'unknown startup warns')
s, events = tick(s, nil, 10000)
equal(#events, 0, 'unknown alone never means power loss')
equal(s.outage_since, nil, 'no fabricated outage')
for _, invalid in ipairs({'', 'OL OB', 'NONSENSE', 'OL CAL', 'OB CAL'}) do
	local v = tick({}, invalid, 100)
	equal(v.outage_since, nil, 'ambiguous status never fabricates outage: ' .. invalid)
end
s = tick({}, 'OB', 100)
s, events = tick(s, 'OL', 699)
equal(s.shutdown_sent, nil, 'restoration before deadline cancels shutdown')
s, events = tick(s, 'OL', 900)
equal(#events, 0, 'canceled event never reappears')
s = tick({}, 'OB', 100)
s, events = tick(s, 'OB', 1000)
equal(events[#events], 'shutdown', 'late polling still enforces deadline')
s, events = tick(s, 'OL', 1, 'boot-b')
equal(#events, 0, 'new boot discards prior monotonic timeline')
equal(s.outage_since, nil, 'prior boot outage cleared')
s = tick({}, 'OB', 100)
equal(pcall(tick, s, 'OB', 90), false, 'same-boot clock regression rejected')
print(count .. ' UPS policy assertions passed')
