# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/nixos/root";
      fsType = "zfs"; options = [ "zfsutil" "X-mount.mkdir" ];
    };

  # Legacy mountpoints deliberately use plain `mount -t zfs`: adding zfsutil
  # delegates to `zfs mount`, which refuses datasets whose mountpoint is
  # `legacy`. `nixpool/nix` is a two-NVMe mirror; the old HDD-resident /nix
  # remains a recovery copy beneath this mount until the migration is proven.
  fileSystems."/nix" =
    { device = "nixpool/nix";
      fsType = "zfs";
      options = [ "X-mount.mkdir" ];
    };

  # Games are deliberately recreatable. Do not turn a failed Steam NVMe into
  # a host boot failure; Steam can repair/re-download its library when back.
  fileSystems."/mnt/steam-nvme" =
    { device = "steampool/steam";
      fsType = "zfs";
      options = [ "nofail" "X-mount.mkdir" ];
    };

  # Compiler caches and build products are reproducible and deliberately live
  # on one NVMe. A missing cache pool must degrade speed, never prevent boot.
  fileSystems."/mnt/devcache" =
    { device = "devpool/devcache";
      fsType = "zfs";
      options = [ "nofail" "X-mount.mkdir" ];
    };

  fileSystems."/home" =
    { device = "rpool/nixos/home";
      fsType = "zfs"; options = [ "zfsutil" "X-mount.mkdir" ];
    };

  fileSystems."/var/lib" =
    { device = "rpool/nixos/var/lib";
      fsType = "zfs"; options = [ "zfsutil" "X-mount.mkdir" ];
    };

  fileSystems."/var/log" =
    { device = "rpool/nixos/var/log";
      fsType = "zfs"; options = [ "zfsutil" "X-mount.mkdir" ];
    };

  # ⛔ bpool is read by GRUB ITSELF and is pinned to `compatibility=grub2`.
  # NEVER `zpool upgrade bpool` -- `zpool status` advises it, and that advice is
  # wrong here; it enables features GRUB cannot parse and the host stops booting.
  # Full explanation at the `grub.zfsSupport` line in zfs.nix.
  fileSystems."/boot" =
    { device = "bpool/nixos/root";
      neededForBoot = true;
      fsType = "zfs"; options = [ "zfsutil" "X-mount.mkdir" ];
    };

  # ESPs are mounted `nofail` so a dirty or absent EFI partition can never strand the
  # machine in emergency mode. An unclean shutdown leaves vfat marked dirty; fsck.vfat
  # then fails the mount, and without `nofail` systemd treats that as fatal at boot
  # (hit 2026-07-25 after force-rebooting out of a wedged display-manager).
  # device-timeout keeps a missing disk from costing the default 90s wait.
  #
  # CAVEAT: with `nofail`, a *silently unmounted* ESP means a later bootloader install
  # would write into the underlying bpool directory instead of the real EFI partition,
  # and the update would not take effect. After any unclean boot, verify with:
  #   mountpoint -q /boot/efi && echo ESP mounted || echo 'ESP NOT MOUNTED — fix before nixos-rebuild boot'
  fileSystems."/boot/efis/ata-WDC_WD101FZBX-00ATAA0_VCKR0ALP-part1" =
    { device = "/dev/disk/by-uuid/4144-CE86";
      fsType = "vfat";
      options = [ "nofail" "x-systemd.device-timeout=10s" ];
    };

  fileSystems."/boot/efis/ata-WDC_WD101FZBX-00ATAA0_VCKR0UGP-part1" =
    { device = "/dev/disk/by-uuid/4146-2DD7";
      fsType = "vfat";
      options = [ "nofail" "x-systemd.device-timeout=10s" ];
    };

  # Bind source is an ESP above; if that failed to mount, this must not be fatal either.
  fileSystems."/boot/efi" =
    { device = "/boot/efis/ata-WDC_WD101FZBX-00ATAA0_VCKR0ALP-part1";
      fsType = "none";
      options = [ "bind" "nofail" ];
    };

  # to get both flatpak steam and native steam to use the same directory
  # fileSystems."/home/pmarreck/.var/app/com.valvesoftware.Steam/.local/share/Steam" = {
  #   device = "/home/pmarreck/.local/share/Steam";
  #   options = [ "bind" ];
  # };

  # Swap moved OFF the USB-docked spinning drives onto NVMe (Peter, 2026-07-31).
  #
  # WHY: the two 10TB drives (sdd/sde) are both on ONE USB bus (usb6), and they
  # carried BOTH rpool (/, /home, /var) AND swap (sdd4/sde4). So memory reclaim
  # saturated the USB channel with paging, every filesystem read then queued
  # behind it, and the compositor blocked in uninterruptible sleep — producing
  # TOTAL GUI freezes: no cursor, no mouse pointer, for minutes. This was bus
  # contention between swap and the root filesystem, not merely a slow disk.
  #
  # Sized 32 GiB, not the previous 309 GiB: measured peak use was 3.8 GiB, and
  # cumulative writes were 32.7 GiB over 93 hours of uptime. Hibernation is NOT
  # enabled on this host (no resume= in /proc/cmdline), so swap does not need to
  # be >= RAM.
  #
  # NVMe wear was Peter's concern and the numbers answer it: both NVMes report
  # "Percentage Used: 1%" after 31.4 TB written, and observed swap traffic is
  # ~8.4 GB/day ≈ 3 TB/yr ≈ 0.1%/yr. Placed on nvme0n1 because it is marginally
  # less worn AND its neighbour is devpool rather than steampool, so swap does
  # not contend with game loading.
  #
  # The old USB swap partitions (sdd4/sde4) are deliberately NOT listed. Leaving
  # them at lower priority would let the kernel spill onto the USB bus again
  # once NVMe swap filled — which is the exact failure being removed. They
  # remain on disk, unused, and can be reclaimed as free space later.
  #
  # Follow-up: vm.swappiness was lowered to 10 BECAUSE swap was slow. With swap
  # on NVMe that is now over-conservative; consider restoring ~60.
  swapDevices = [
    { device = "/dev/disk/by-uuid/8bbac7b3-c013-4aa8-b7ca-adff01064770"; } # nvme0n1p3, label swap-nvme0
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp68s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
